apiVersion: apps/v1
kind: Deployment
metadata: 
  name: llm-api
  labels:
    app: llm-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-api
 
  template:
    metadata:
      labels:
        app: llm-api
    spec:
      containers:
      - name: llm-api-container
        image: mlops-llm-platform:v1
        imagePullPolicy: Never

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet: 
            path: "/health"
            port: 8000

          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: "/health"
            port: 8000

          initialDelaySeconds: 15
          periodSeconds: 20