apiVersion: v1
kind: Service
metadata:
  name: llm-api-service
spec:
  type: NodePort
  selector: 
    app: llm-api
  ports:
    - port: {{.Values.service.port}}
      targetPort: 8000
      nodePort: {{.Values.service.nodePort}}